[tool.poetry]
name = "logger"
version = "0.1.11"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
readme = "README.md"
packages = [{include = "logger"}]

[tool.poetry.dependencies]
python = "^3.9"
dependency-injector = "^4.41.0"
pandas = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
